### ISSUE TITLE
refactor: Change Keploy Server port from 8081 to 6789 in server config 

### ISSUE THREAD

**Issue by Sarthak160** [keploy/samples-go#21]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

- Have to refactor all readme / docs and config 
- Have to change port from **(8081 to 6789)** in **Keploy's Server** config .
- All demo apps should apply the same .
- Including [Typscript](https://github.com/keploy/typescript-sdk) and [Java](https://github.com/keploy/java-sdk) SampleApps too .

### Why should this be worked on?

Since Keploy's default port is changed , anybody who will use demo applications will not be able to run Keploy and have to change the port by itself .

**Comment by MagnaibayarMN** [comment]
Hello, Can i contribute?

**Comment by nehagup** [comment]
@MagnaibayarMN sure

**Comment by MagnaibayarMN** [comment]
Hello? Please review those merge requests: 

- https://github.com/keploy/samples-go/pull/22
- https://github.com/keploy/typescript-sdk/pull/36
- https://github.com/keploy/java-sdk/pull/56
